import * as THREE from 'three';
import {GLTFLoader} from 'three/addons/loaders/GLTFLoader.js';

(async()=>{const host=document.querySelector('#car-stage');try{
const renderer=new THREE.WebGLRenderer({antialias:true,alpha:false});renderer.setPixelRatio(Math.min(devicePixelRatio,1.5));renderer.setSize(host.clientWidth,host.clientHeight);renderer.setClearColor(0x0c0e11);renderer.toneMapping=THREE.ACESFilmicToneMapping;renderer.toneMappingExposure=1.03;renderer.shadowMap.enabled=true;renderer.shadowMap.type=THREE.PCFSoftShadowMap;renderer.shadowMap.autoUpdate=false;renderer.shadowMap.needsUpdate=true;document.querySelector('#car-stage').append(renderer.domElement);renderer.domElement.setAttribute('aria-hidden','true');
let dirty=true;const scene=new THREE.Scene();const pmrem=new THREE.PMREMGenerator(renderer);const studio=new THREE.Scene();studio.background=new THREE.Color(0x080a0e);
function panel(w,h,x,y,z,power){const material=new THREE.MeshBasicMaterial({color:new THREE.Color(1,1,1).multiplyScalar(power),side:THREE.DoubleSide});const panel=new THREE.Mesh(new THREE.PlaneGeometry(w,h),material);panel.position.set(x,y,z);panel.lookAt(0,.6,0);studio.add(panel);}
panel(9,1.8,0,5,1,5);panel(8,1.2,1,2.4,-4,4);panel(3,3,-5,2,3,1.5);
scene.environment=pmrem.fromScene(studio,.06).texture;studio.traverse(o=>{if(o.isMesh){o.geometry.dispose();o.material.dispose();}});pmrem.dispose();
const camera=new THREE.PerspectiveCamera(35,host.clientWidth/host.clientHeight,.01,100);
const light=new THREE.DirectionalLight(0xf2f4ff,1.8);light.position.set(-3,7,5);light.castShadow=true;light.shadow.mapSize.set(2048,2048);Object.assign(light.shadow.camera,{left:-5,right:5,top:5,bottom:-5,near:.1,far:20});light.shadow.normalBias=.025;light.shadow.bias=-.0001;scene.add(light);scene.add(new THREE.HemisphereLight(0xd7e8ff,0x16191e,.38));const rim=new THREE.DirectionalLight(0xc8d9ff,2.1);rim.position.set(3,4,-4);scene.add(rim);
const ground=new THREE.Mesh(new THREE.PlaneGeometry(100,100),new THREE.MeshBasicMaterial({color:0x0c0e11,toneMapped:false}));ground.rotation.x=-Math.PI/2;ground.position.y=-.01;ground.receiveShadow=true;scene.add(ground);const shadow=new THREE.Mesh(new THREE.PlaneGeometry(20,20),new THREE.ShadowMaterial({opacity:.3}));shadow.rotation.x=-Math.PI/2;shadow.receiveShadow=true;scene.add(shadow);

let gltf;const embedded=document.querySelector('#unused-model-data');if(embedded){const raw=atob(embedded.textContent.trim());const bytes=new Uint8Array(raw.length);for(let i=0;i<raw.length;i++)bytes[i]=raw.charCodeAt(i);gltf=await new GLTFLoader().parseAsync(bytes.buffer,'');}else{gltf=await new GLTFLoader().loadAsync('./assets/porsche-vanta.glb');}const car=gltf.scene;const door1=car.getObjectByName('door_1'),door2=car.getObjectByName('door_2');if(door1&&door2){door2.position.copy(door1.position);door2.quaternion.copy(door1.quaternion);door2.scale.copy(door1.scale);}car.updateMatrixWorld(true);let box=new THREE.Box3().setFromObject(car),size=box.getSize(new THREE.Vector3());if(size.z>size.x)car.rotation.y=Math.PI/2;
car.updateMatrixWorld(true);box.setFromObject(car);size=box.getSize(new THREE.Vector3());car.scale.multiplyScalar(4.65/Math.max(size.x,size.z));car.updateMatrixWorld(true);box.setFromObject(car);const center=box.getCenter(new THREE.Vector3());car.position.add(new THREE.Vector3(-center.x,-box.min.y,-center.z));car.updateMatrixWorld(true);
const paint=[];let count=0;car.traverse(o=>{if(!o.isMesh)return;count++;o.castShadow=true;o.receiveShadow=true;const adjust=m=>{if(m.name==='invisible_all'){o.visible=false;}if(m.transparent)m.depthWrite=false;if(m.name==='body_main'){const fresh=new THREE.MeshPhysicalMaterial();THREE.MeshStandardMaterial.prototype.copy.call(fresh,m);fresh.clearcoat=1;fresh.clearcoatRoughness=.09;fresh.metalness=.62;fresh.roughness=.22;fresh.roughnessMap=null;fresh.metalnessMap=null;fresh.normalScale.set(.12,.12);fresh.envMapIntensity=.9;fresh.name=m.name;fresh.userData.originalColor=m.color.clone();fresh.color.set(0x242a32);paint.push(fresh);return fresh;}return m;};o.material=Array.isArray(o.material)?o.material.map(adjust):adjust(o.material);});scene.add(car);

const reduced=matchMedia('(prefers-reduced-motion: reduce)');let visible=true,progress=window.VANTA_PROGRESS||0,current=progress,raf=0,last=0;
function render(now=performance.now()){const aspect=host.clientWidth/host.clientHeight;const fit=Math.max(1,.95/aspect);const angle=.66+current*1.87;const radius=(7.7-.25*Math.sin(current*Math.PI))*fit;camera.position.set(Math.cos(angle)*radius,(1.85+.22*Math.sin(current*Math.PI))*fit,Math.sin(angle)*radius);camera.lookAt(0,.65,0);const drift=reduced.matches?0:Math.sin(now*.00023);light.position.x=-3+drift*.9;rim.intensity=1.9+(drift+1)*.18;renderer.render(scene,camera);}
function tick(now){raf=0;if(!visible||document.hidden)return;if(now-last>45){current=reduced.matches?progress:current+(progress-current)*.2;if(Math.abs(progress-current)<.0001)current=progress;render(now);last=now;}if(!reduced.matches)raf=requestAnimationFrame(tick);}
function request(){if(!raf&&!document.hidden&&visible)raf=requestAnimationFrame(tick);}
addEventListener('vanta:progress',e=>{progress=e.detail.progress;visible=e.detail.visible;request();});document.addEventListener('visibilitychange',request);reduced.addEventListener('change',request);
addEventListener('resize',()=>{camera.aspect=host.clientWidth/host.clientHeight;camera.updateProjectionMatrix();renderer.setSize(host.clientWidth,host.clientHeight);render();request();});
render();host.classList.add('loaded');dispatchEvent(new Event('vanta:ready'));request();window.__vantaLP={renderer,scene,camera,car,get progress(){return progress;},pause(){visible=false;},render};
renderer.domElement.addEventListener('webglcontextlost',()=>{host.classList.remove('loaded');dispatchEvent(new Event('vanta:error'));});
}catch(e){console.error('VANTA 3D:',e);dispatchEvent(new Event('vanta:error'));}})();
