(()=>{'use strict';const config=window.VANTA_CONFIG||{},dialog=document.querySelector('#contact-dialog'),reduced=matchMedia('(prefers-reduced-motion: reduce)');document.querySelector('#year').textContent=new Date().getFullYear();document.querySelectorAll('[data-contact]').forEach(button=>button.addEventListener('click',()=>{const number=String(config.whatsapp||'').replace(/\D/g,'');if(number){window.open('https://wa.me/'+number+'?text='+encodeURIComponent(config.message||''),'_blank','noopener,noreferrer');return;}dialog.showModal();}));dialog.querySelectorAll('button').forEach(b=>b.addEventListener('click',()=>dialog.close()));dialog.addEventListener('click',e=>{if(e.target===dialog){const r=dialog.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)dialog.close();}});
const section=document.querySelector('.car-story'),button=document.querySelector('#activate-3d'),loader=document.querySelector('#car-loader'),fill=document.querySelector('#progress-fill');const beats=[['01 / REVELAR','A profundidade<br>de cada reflexo.','Correção de pintura para revelar a clareza e a expressão do acabamento.'],['02 / PROTEGER','O cuidado que<br>acompanha o uso.','Proteção pensada para preservar a superfície, sem esconder suas linhas.'],['03 / PRESERVAR','A essência,<br>por inteiro.','Uma visão completa do automóvel. Do primeiro olhar ao último detalhe.']];let last=-1,pending=false,started=false;
function update(){pending=false;const rect=section.getBoundingClientRect(),progress=reduced.matches?0:Math.max(0,Math.min(1,-rect.top/Math.max(1,section.offsetHeight-innerHeight)));fill.style.width=(progress*100)+'%';const index=Math.min(2,Math.floor(progress*3));if(index!==last){last=index;if(!reduced.matches&&document.querySelector('.story-copy').animate)document.querySelector('.story-copy').animate([{opacity:.15,transform:'translateY(10px)'},{opacity:1,transform:'translateY(0)'}],{duration:600,easing:'cubic-bezier(.2,.7,.2,1)'});document.querySelector('#story-index').textContent=beats[index][0];document.querySelector('#story-title').innerHTML=beats[index][1];document.querySelector('#story-description').textContent=beats[index][2];}window.VANTA_PROGRESS=progress;dispatchEvent(new CustomEvent('vanta:progress',{detail:{progress,visible:rect.bottom>0&&rect.top<innerHeight}}));}
function request(){if(!pending){pending=true;requestAnimationFrame(update);}}addEventListener('scroll',request,{passive:true});addEventListener('resize',request);update();
function start(){if(started)return;started=true;button.hidden=true;loader.hidden=false;const script=document.createElement('script');script.src='./js/car.js';script.onerror=()=>{loader.textContent='Continue explorando pelas imagens.';};document.body.append(script);}button.addEventListener('click',start);addEventListener('vanta:ready',()=>{loader.hidden=true;request();});addEventListener('vanta:error',()=>{loader.textContent='Continue explorando pelas imagens.';});
if('IntersectionObserver'in window){const observer=new IntersectionObserver(entries=>{if(entries.some(e=>e.isIntersecting)&&innerWidth>800&&!reduced.matches&&!navigator.connection?.saveData){start();observer.disconnect();}},{rootMargin:'450px'});observer.observe(section);}
})();

/* Direção de movimento: entrada, luz, profundidade e ritmo editorial. */
(()=>{const reduced=matchMedia('(prefers-reduced-motion: reduce)'),hero=document.querySelector('.hero'),toggle=document.querySelector('.menu-toggle'),nav=document.querySelector('#main-nav');document.body.classList.add('menu-enhanced');nav.hidden=true;function closeMenu(){nav.hidden=true;toggle.setAttribute('aria-expanded','false');}toggle.addEventListener('click',()=>{nav.hidden=!nav.hidden;toggle.setAttribute('aria-expanded',String(!nav.hidden));});nav.querySelectorAll('a').forEach(a=>a.addEventListener('click',closeMenu));document.addEventListener('keydown',e=>{if(e.key==='Escape'&&!nav.hidden){closeMenu();toggle.focus();}});document.addEventListener('click',e=>{if(!nav.contains(e.target)&&!toggle.contains(e.target))closeMenu();});
const items=document.querySelectorAll('.section-label,.manifesto-bottom,.services-intro,.service-list details,.detail-copy,.process-heading,.process-grid article,.motion-text,.contact>.eyebrow,.contact-row,.contact-bottom');items.forEach((el,i)=>{el.classList.add('reveal-item');if(el.matches('.process-grid article'))el.style.setProperty('--reveal-delay',(Array.from(el.parentElement.children).indexOf(el)*110)+'ms');});
if('IntersectionObserver'in window){const reveals=new IntersectionObserver(entries=>entries.forEach(e=>{if(e.isIntersecting){e.target.classList.add('is-visible');reveals.unobserve(e.target);}}),{threshold:.12,rootMargin:'0px 0px -30px 0px'});items.forEach(el=>reveals.observe(el));if(!reduced.matches)document.body.classList.add('motion-ready');}else{items.forEach(el=>el.classList.add('is-visible'));}
const photos=[...document.querySelectorAll('.scene-image,.motion-scene')],lines=[...document.querySelectorAll('.manifesto-lines>span')],bar=document.querySelector('.reading-progress span');let pending=false;
function paint(){pending=false;const h=innerHeight,r=hero.getBoundingClientRect();hero.classList.toggle('is-offscreen',r.bottom<=0);const pageProgress=scrollY/Math.max(1,document.documentElement.scrollHeight-h);bar.style.transform='scaleX('+pageProgress+')';if(reduced.matches)return;if(r.bottom>0){hero.style.setProperty('--hero-y',Math.min(scrollY*.10,90)+'px');hero.style.setProperty('--hero-scale',String(1+Math.min(scrollY/h,1)*.025));hero.style.setProperty('--hero-atmosphere-y',Math.min(scrollY*.04,40)+'px');}photos.forEach(el=>{const r=el.getBoundingClientRect();if(r.top<h&&r.bottom>0){const p=(h*.5-(r.top+r.height*.5))/h;el.style.setProperty('--photo-y',(Math.max(-1,Math.min(1,p))*55)+'px');}});lines.forEach(el=>{const r=el.getBoundingClientRect();const p=Math.max(0,Math.min(1,(h*.85-r.top)/(h*.38)));const v=Math.round(82+p*145);el.style.setProperty('--line-color',`rgb(${v},${v+3},${v-2})`);});}
function request(){if(!pending){pending=true;requestAnimationFrame(paint);}}addEventListener('scroll',request,{passive:true});addEventListener('resize',request);request();
if(matchMedia('(pointer:fine)').matches){let pointerFrame=false,px=.5;hero.addEventListener('pointermove',e=>{if(reduced.matches)return;px=e.clientX/innerWidth;if(!pointerFrame){pointerFrame=true;requestAnimationFrame(()=>{pointerFrame=false;hero.style.setProperty('--light-x',(35+px*30)+'%');hero.style.setProperty('--hero-x',((px-.5)*9)+'px');});}});hero.addEventListener('pointerleave',()=>{hero.style.setProperty('--hero-x','0px');});}
reduced.addEventListener('change',()=>{document.body.classList.toggle('motion-ready',!reduced.matches);if(reduced.matches){items.forEach(el=>el.classList.add('is-visible'));hero.style.setProperty('--hero-y','0px');hero.style.setProperty('--hero-x','0px');photos.forEach(el=>el.style.setProperty('--photo-y','0px'));}request();});
document.querySelectorAll('.service-list details').forEach(el=>el.addEventListener('toggle',()=>{if(el.open&&!reduced.matches&&el.querySelector('.service-body').animate)el.querySelector('.service-body').animate([{opacity:0,transform:'translateY(-8px)'},{opacity:1,transform:'translateY(0)'}],{duration:450,easing:'ease-out'});}));
})();

/* V03: cenas selecionáveis. O visitante controla a troca. */
(()=>{const hero=document.querySelector('.hero'),tabs=[...document.querySelectorAll('[data-chapter]')],images=[...document.querySelectorAll('.chapter-image')],pause=document.querySelector('.motion-toggle');const chapters=[['Além do tempo.','Preserve o extraordinário.'],['A arte do cuidado.','Precisão que se revela na superfície.'],['A essência segue.','Feito para rodar. Preservado para durar.']];tabs.forEach((button,index)=>button.addEventListener('click',()=>{tabs.forEach((tab,i)=>{tab.classList.toggle('active',i===index);tab.setAttribute('aria-pressed',String(i===index));images[i].classList.toggle('active',i===index);});document.querySelector('#hero-title').textContent=chapters[index][0];document.querySelector('#chapter-description').textContent=chapters[index][1];document.querySelector('#chapter-status').textContent='Cena '+(index+1)+' de 3. '+chapters[index][0];}));pause.addEventListener('click',()=>{const paused=hero.classList.toggle('motion-paused');pause.setAttribute('aria-pressed',String(paused));pause.setAttribute('aria-label',paused?'Retomar movimento das imagens':'Pausar movimento das imagens');pause.querySelector('.motion-label').textContent=paused?'RETOMAR':'PAUSAR';pause.querySelector('span').textContent=paused?'▷':'Ⅱ';});})();
